/* 003 (project photos) in a private Postgres, with the storage service's tables imitated. See local.mjs for how to run. */
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
const { PGlite } = createRequire(new URL('../../web/package.json', import.meta.url))('@electric-sql/pglite');
const repo = new URL('../', import.meta.url).pathname;
const db = new PGlite();
const results = [];
const check = (name, ok, detail = '') => results.push(`${ok ? 'PASS' : 'FAIL'}  ${name}${detail ? ' — ' + String(detail).slice(0, 200) : ''}`);
const fails = async (sql) => { try { await db.exec(sql); return false; } catch (e) { return String(e.message || e); } };
await db.exec(`
  create role anon nologin; create role authenticated nologin; create role service_role nologin;
  create schema auth; create table auth.users (id uuid primary key default gen_random_uuid(), email text);
  create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
  grant usage on schema auth to anon, authenticated; grant usage on schema public to anon, authenticated;
  alter default privileges in schema public grant all on tables to anon, authenticated;
  alter default privileges in schema public grant all on functions to anon, authenticated;
  -- the storage service, imitated: the two tables and the helper the rules use; RLS on, everything granted
  create schema storage; grant usage on schema storage to anon, authenticated;
  create table storage.buckets (id text primary key, name text, public boolean, file_size_limit bigint, allowed_mime_types text[]);
  create table storage.objects (id uuid primary key default gen_random_uuid(), bucket_id text references storage.buckets(id), name text, owner uuid, created_at timestamptz default now());
  alter table storage.objects enable row level security;
  grant all on storage.objects to anon, authenticated;
  create function storage.foldername(name text) returns text[] language sql immutable as $$ select (string_to_array(name, '/'))[1:array_length(string_to_array(name, '/'), 1) - 1] $$;
`);
await db.exec(readFileSync(repo + '001_accounts_projects_forms.sql', 'utf8').replace(/create extension if not exists pgcrypto;/, ''));
const three = readFileSync(repo + '003_project_files.sql', 'utf8');
await db.exec(three); await db.exec(three);
check('003 runs cleanly, twice', true);
const ADMIN = '00000000-0000-4000-8000-0000000000aa', A = '00000000-0000-4000-8000-0000000000bb', B = '00000000-0000-4000-8000-0000000000cc';
await db.exec(`insert into auth.users (id, email) values ('${ADMIN}', 'owner@tarmem.sa'), ('${A}', 'a@example.com'), ('${B}', 'b@example.com');
  insert into public.profiles (id, role, full_name, mobile, city) values ('${ADMIN}', 'admin', 'Owner', '0500000000', 'riyadh'), ('${A}', 'homeowner', 'Aaa', '0511111111', 'riyadh'), ('${B}', 'homeowner', 'Bbb', '0522222222', 'riyadh');`);
const as = async (role, sub) => { await db.exec(`reset role; select set_config('request.jwt.claim.sub', '${sub || ''}', false); set role ${role};`); };
await as('authenticated', A);
const pa = (await db.query(`insert into public.projects (title, trade, description, city, budget_min, budget_max, timing) values ('Kitchen', 'kitchen', 'A kitchen', 'riyadh', 1000, 2000, 'month') returning id`)).rows[0].id;
await as('authenticated', B);
const pb = (await db.query(`insert into public.projects (title, trade, description, city, budget_min, budget_max, timing) values ('Bath', 'kitchen', 'A bath', 'riyadh', 1000, 2000, 'month') returning id`)).rows[0].id;
const put = (owner, project, file = 'x.jpg', bucket = 'project-files') => `insert into storage.objects (bucket_id, name) values ('${bucket}', '${owner}/${project}/${file}')`;
await as('authenticated', A);
check('owner: can add a file to their own project', !(await fails(put(A, pa))));
check("owner: cannot add a file under somebody else's id", Boolean(await fails(put(B, pb))));
check("owner: cannot add a file to somebody else's project, even under their own id", Boolean(await fails(put(A, pb))));
check('owner: cannot add a file to a project that does not exist, or outside a project folder', Boolean(await fails(put(A, '00000000-0000-4000-8000-00000000dead'))) && Boolean(await fails(`insert into storage.objects (bucket_id, name) values ('project-files', '${A}/loose.jpg')`)));
check('owner: sees their own files', (await db.query(`select count(*)::int n from storage.objects`)).rows[0].n === 1);
check('owner: cannot delete or rename a file', (await db.query(`delete from storage.objects returning id`)).rows.length === 0 && (await db.query(`update storage.objects set name = 'x' returning id`)).rows.length === 0);
await as('authenticated', B);
check("another customer: sees none of the first one's files", (await db.query(`select count(*)::int n from storage.objects`)).rows[0].n === 0);
await as('anon');
check('visitor: sees no files and can add none', (await db.query(`select count(*)::int n from storage.objects`)).rows[0].n === 0 && Boolean(await fails(put(A, pa, 'y.jpg'))));
await as('authenticated', ADMIN);
check('admin: sees every project\'s files', (await db.query(`select count(*)::int n from storage.objects`)).rows[0].n === 1);
await db.exec('reset role');
check('the bucket is private, 10 MB, images + PDF', (await db.query(`select public, file_size_limit, array_length(allowed_mime_types, 1) n from storage.buckets where id = 'project-files'`)).rows[0].public === false);
console.log(results.join('\n')); process.exit(results.some((r) => r.startsWith('FAIL')) ? 1 : 0);
