/* Words the real-accounts pages need that the design does not have: it signs people in with a
   mobile code and Nafath, neither of which is connected yet, so the public site uses email and
   a password for now. Wording here is a first draft for the owner to review. */

export const PLATFORM_COPY = {
  ar: {
    notice: 'إطلاق مبكر: انشر مشروعك، واستقبل عروض مقاولين موثّقين، ووقّع الاتفاقية عبر الموقع. يوثّق فريق ترميم المقاولين يدويًا حاليًا، والدفع عبر الموقع قيد التفعيل.',
    signInTitle: 'سجّل دخولك', signUpTitle: 'أنشئ حسابك',
    signInLede: 'ادخل ببريدك الإلكتروني وكلمة المرور لمتابعة مشاريعك.',
    signUpLede: 'حساب واحد لنشر مشاريعك ومتابعتها. يستغرق دقيقة.',
    pendingPost: 'مشروعك جاهز. أنشئ حسابك أو سجّل دخولك لننشره باسمك.',
    email: 'البريد الإلكتروني', password: 'كلمة المرور', passwordHint: '8 أحرف على الأقل',
    name: 'الاسم الكامل', mobile: 'رقم الجوال', mobilePh: '05XXXXXXXX', city: 'المدينة',
    agree: 'أوافق على', terms: 'الشروط والأحكام', and: 'و', privacy: 'سياسة الخصوصية',
    signIn: 'تسجيل الدخول', signUp: 'إنشاء الحساب', working: 'لحظة…',
    contractorNote: 'مقاول؟ التسجيل للمقاولين يتم عبر', contractorLink: 'طلب الانضمام',
    forgot: 'نسيت كلمة المرور؟', forgotLink: 'أعد تعيينها', forgotTitle: 'إعادة تعيين كلمة المرور', forgotLede: 'اكتب بريدك الإلكتروني ونرسل لك رابطًا لاختيار كلمة مرور جديدة.', forgotSend: 'أرسل الرابط',
    forgotSent: 'إذا كان هذا البريد مسجّلًا لدينا فستصلك رسالة خلال دقائق فيها رابط لاختيار كلمة مرور جديدة. تحقق من البريد غير المرغوب أيضًا.', backToSignIn: 'العودة لتسجيل الدخول',
    newPassTitle: 'اختر كلمة مرور جديدة', newPassLede: 'اكتب كلمة المرور الجديدة لحسابك.', newPassSave: 'حفظ كلمة المرور',
    closeBtnReal: 'حذف حسابي', closeYesReal: 'نعم، احذف حسابي', closeQReal: 'حذف حسابك وبياناتك نهائيًا؟', closeBodyReal: 'يُحذف اسمك ورقمك وبريدك وصورك وبياناتك البنكية ورسائلك فورًا، ويُغلق الحساب ولا يمكن استعادته. تبقى المشاريع والعطاءات والاتفاقيات سجلات بلا اسم. مشروع جارٍ يجب إكماله أولًا.', closeDone: 'تم حذف حسابك وبياناتك الشخصية. شكرًا لك، ونتمنى أن نراك مجددًا.', erased: 'تم حذف الحساب.',
    otpTitle: 'وثّق رقم جوالك', otpLede: 'أرسلنا رمزًا من ستة أرقام عبر واتساب إلى', otpCode: 'الرمز', otpVerify: 'تأكيد الرمز', otpResend: 'أعد إرسال الرمز', otpLater: 'لاحقًا', otpSent: 'أُرسل الرمز. صالح لعشر دقائق.',
    newPassAgain: 'أعد كتابة كلمة المرور', resetDoneTitle: 'تم تغيير كلمة المرور', resetDoneLede: 'أنت الآن مسجّل الدخول، وستصلك رسالة تأكيد على بريدك.', resetDoneGo: 'افتح لوحتك',
    resetExpiredTitle: 'انتهت صلاحية هذا الرابط', resetExpiredLede: 'رابط إعادة التعيين يعمل مرة واحدة ولوقت محدود. اطلب رابطًا جديدًا من صفحة تسجيل الدخول.', resetExpiredGo: 'إلى تسجيل الدخول',
    confirmSent: 'أرسلنا رسالة تأكيد إلى بريدك. افتح الرابط الذي فيها ثم سجّل دخولك.',
    err: {
      email: 'اكتب بريدًا إلكترونيًا صحيحًا.', password: 'كلمة المرور 8 أحرف على الأقل.',
      pwned: 'كلمة المرور هذه ظهرت في تسريبات بيانات سابقة على الإنترنت، فهي غير آمنة. اختر كلمة مرور أخرى.',
      name: 'اكتب اسمك الكامل.', mobile: 'اكتب رقم جوال صحيحًا، مثل 0551234567.', agree: 'يلزم قبول الشروط وسياسة الخصوصية.',
      wrong: 'البريد أو كلمة المرور غير صحيحة.', exists: 'يوجد حساب بهذا البريد. سجّل دخولك بدلًا من ذلك.',
      mobileTaken: 'رقم الجوال هذا مسجّل لحساب آخر. سجّل الدخول إليه، أو استخدم رقمًا آخر.', passwordMatch: 'كلمتا المرور غير متطابقتين.',
      caseReply: 'تعذّر إرسال الرد. حاول مرة أخرى.', activeProject: 'لديك مشروع جارٍ. أكمله أو تواصل مع الفريق أولًا.', otpOff: 'توثيق الجوال غير مفعّل حاليًا.', otpWrong: 'الرمز غير صحيح أو انتهت صلاحيته. اطلب رمزًا جديدًا.',
      unconfirmed: 'أكّد بريدك من الرسالة التي أرسلناها، ثم سجّل دخولك.', rate: 'محاولات كثيرة. انتظر دقيقة ثم حاول مجددًا.',
      network: 'تعذّر الاتصال. تحقق من الإنترنت وحاول مجددًا.', generic: 'حدث خطأ غير متوقع. حاول مجددًا.',
      waOff: 'تحديثات واتساب لم تُفعَّل بعد.', waLimit: 'وصلت إلى الحد اليومي للرسائل التجريبية. جرّب غدًا.', waNumber: 'اكتب رقم جوال سعودي، مثل 0551234567.',
      notHomeowner: 'نشر المشاريع متاح لحسابات أصحاب المنازل فقط.', tooMany: 'لديك 10 مشاريع مفتوحة. أغلق أحدها قبل نشر مشروع جديد.',
      title: 'اكتب عنوانًا للمشروع (3 أحرف على الأقل).', desc: 'صف المشروع بجملة على الأقل.', budget: 'اكتب ميزانية صحيحة: الحد الأدنى لا يتجاوز الأعلى، والأعلى لا يتجاوز 1,000,000 ريال.',
    },
    posted: 'نُشر مشروعك. يراجعه فريق ترميم ويتواصل معك على جوالك خلال يوم عمل.',
    postedNoBids: 'نُشر مشروعك ويراه المقاولون الموثّقون الآن. تظهر عروضهم هنا فور وصولها، ويصلك بريد مع كل عرض جديد.',
    publish: 'نشر المشروع',
    contactSent: 'وصلتنا رسالتك. نرد عليك خلال يوم عمل.', contactFailed: 'تعذّر إرسال الرسالة. حاول مجددًا.',
    verifiedMessage: (person: string, company: string, link: string, hasAccount: boolean) => hasAccount
      ? `مرحبًا ${person}، معك فريق ترميم.\nتم توثيق حساب «${company}» وأصبح جاهزًا للاستخدام. سجّل دخولك بالبريد وكلمة المرور اللذين أنشأتهما:\n${link}`
      : `مرحبًا ${person}، معك فريق ترميم.\nتم قبول طلب «${company}». لإكمال التسجيل أنشئ حسابك من صفحة انضمام المقاولين:\n${link.replace('/signin', '/join')}`,
    coPendingTitle: 'حسابك قيد التوثيق', coPendingNote: 'استلمنا طلبك وأنشأنا حسابك. يراجع فريق ترميم بياناتك ويتواصل معك على جوالك، وتصلك رسالة على بريدك فور تفعيل الحساب. بعدها تظهر لك المشاريع المفتوحة هنا.',
    choseNote: 'اخترت عرض «{co}». يتواصل فريق ترميم معك ومع المقاول لإتمام الاتفاقية وبدء العمل.', chosenNote: 'اختار صاحب المنزل عرضك. يتواصل معك فريق ترميم لإتمام الاتفاقية وبدء العمل.',
    paySoonTitle: 'الدفع عبر الموقع قيد التفعيل', paySoonNote: 'وقّع الطرفان الاتفاقية، وهي محفوظة باسميكما وتاريخ التوقيع. يتواصل فريق ترميم معكما لترتيب الدفعة الأولى وبدء العمل. عند تفعيل الدفع عبر الموقع تُودَع الدفعات هنا وتُصرف مع اعتماد كل مرحلة.', refresh: 'تحديث',
    stagesAfterAward: 'تبدأ المراحل بعد إسناد المشروع إلى مقاول.',
    stagesSoon: 'تبدأ المراحل بعد ترتيب الدفعة الأولى. اعتماد المراحل وصرف دفعاتها عبر الموقع يُفعَّل مع الدفع.',
    settingsMobileNote: 'يُستخدم للتواصل معك ولرسائل واتساب.', settingsEmail: 'البريد الإلكتروني (لتسجيل الدخول)',
    protectNoNafath: 'يراجع فريق ترميم بيانات المنشأة وسجلها التجاري قبل ظهور الملف.',
    postedNoBidsWa: 'نُشر مشروعك ويراه المقاولون الموثّقون الآن. تظهر عروضهم هنا فور وصولها، ويصلك بريد ورسالة واتساب مع كل عرض جديد.',
    msgsNoThread: 'تفتح المراسلة مع المقاول عند وصول أول عطاء على مشروعك.', msgsEmpty: 'لا رسائل بعد. اكتب أول رسالة، ويصل الطرف الآخر تنبيه بالبريد وواتساب.', msgsWith: 'المحادثة مع', msgFailed: 'تعذّر إرسال الرسالة. حاول مجددًا.', msgsHomeowner: 'صاحب المنزل', msgsContractor: 'المقاول',
    msgsSoon: 'المراسلة داخل المشروع قيد التفعيل. حتى ذلك الحين يتواصل معكما فريق ترميم بالبريد وواتساب، وتبقى العروض والاتفاقية والملفات هنا.', msgsFrom: 'ترميم',
    waSub: 'ترسل ترميم تحديثات مشروعك إلى واتساب: العروض الجديدة، وقبول العرض، وتوقيع الاتفاقية، والمراحل. في كل رسالة زر يفتح المشروع مباشرة.', waNumberNote: 'هذا رقم جوال حسابك؛ تغييره هنا يغيّره في حسابك أيضًا.',
    waPreview: 'تحديث حالة مشروعك رقم P-2001 في ترميم: تم استلام العطاء رقم 3 من مؤسسة البناء المتقن بقيمة 52,000 ريال ومدة تنفيذ 30 يوم. التفاصيل في صفحة المشروع. [افتح المشروع]',
    settingsSaved: 'حُفظت إعداداتك.', emailLocked: 'لتغيير بريد تسجيل الدخول راسل فريق ترميم.', closeTopic: 'طلب إغلاق الحساب', closeBody: 'يطلب صاحب الحساب إغلاق حسابه.',
    companyLocked: 'اسم المنشأة هو الاسم الموثّق لدى ترميم ولا يُغيَّر من هنا. أعده كما كان، ولتغييره راسل فريق ترميم.', noWorkYet: 'لا مشاريع مكتملة عبر ترميم بعد', noReviewsYet: 'لا تقييمات بعد',
    pfAdd: 'أضف صورًا من أعمالك', pfCaption: 'وصف قصير للصور التالية (اختياري)', pfCaptionPh: 'مثال: مطبخ في حي العارض، 2026', pfHint: 'حتى 12 صورة، JPG أو PNG، 8 ميغابايت للصورة. تظهر لأصحاب المنازل الذين يقارنون العروض.', pfRemove: 'حذف', pfFull: 'وصلت إلى الحد الأقصى (12 صورة). احذف صورة لتضيف أخرى.', pfFailed: 'تعذّر رفع الصورة. حاول مجددًا.',
    wrTitle: 'طلبات بانتظار التأكيد', wrNote: 'يبقى الطلب هنا حتى تتأكد من وصول المبلغ عند مزود الدفع أو البنك. التأكيد يُثبت المبلغ في محفظة صاحبه؛ الرفض يلغيه.', wrNone: 'لا طلبات بانتظار التأكيد.', wrDeposit: 'إيداع', wrPayout: 'تحويل', wrConfirm: 'تأكيد الوصول', wrPaid: 'تم التحويل', wrReject: 'رفض',
    coRefresh: 'تحديث الحالة', bidsSoonTitle: 'تقديم العروض يفتح قريبًا', bidsSoonNote: 'حسابك موثّق ويمكنك تصفّح المشاريع المفتوحة. تقديم العروض من الموقع قيد الإطلاق؛ إلى ذلك الحين راسل فريق ترميم بشأن المشروع الذي يهمّك.',
    coPassword: 'اختر كلمة مرور لحسابك', coEmailNeeded: 'اكتب بريدك الإلكتروني: به تسجّل دخولك بعد التوثيق.', coCreate: 'إرسال الطلب وإنشاء الحساب',
    uploading: 'جارٍ رفع الملفات…', uploadFailed: 'تعذّر رفع هذا الملف. حاول مجددًا من تبويب الملفات.',
    fileErr: { type: 'الملفات المسموحة: صور JPG وPNG وملفات PDF.', size: 'الحد الأقصى لحجم الملف 10 ميغابايت.', count: 'الحد الأقصى 10 ملفات للمشروع.' },
    joinSent: 'وصلنا طلبك. يتواصل معك فريق ترميم لاستكمال التوثيق.', joinSend: 'إرسال الطلب', inbox: 'الوارد', inboxOpen: 'افتح الوارد: المشاريع والطلبات والرسائل ←',
  },
  en: {
    notice: 'Early access: post your project, receive bids from verified contractors, and sign the agreement on the site. The Tarmem team verifies contractors by hand for now, and payment on the site is being set up.',
    signInTitle: 'Sign in', signUpTitle: 'Create your account',
    signInLede: 'Use your email and password to follow your projects.',
    signUpLede: 'One account to post and follow your projects. It takes a minute.',
    pendingPost: 'Your project is ready. Create an account or sign in and we will post it under your name.',
    email: 'Email', password: 'Password', passwordHint: 'At least 8 characters',
    name: 'Full name', mobile: 'Mobile number', mobilePh: '05XXXXXXXX', city: 'City',
    agree: 'I agree to the', terms: 'Terms', and: 'and', privacy: 'Privacy Policy',
    signIn: 'Sign in', signUp: 'Create account', working: 'One moment…',
    contractorNote: 'A contractor? Contractors join through the', contractorLink: 'application form',
    forgot: 'Forgot your password?', forgotLink: 'Reset it', forgotTitle: 'Reset your password', forgotLede: 'Enter your email and we will send you a link to choose a new password.', forgotSend: 'Send the link',
    forgotSent: 'If this email has an account, a message with a link to choose a new password arrives within minutes. Check your spam folder too.', backToSignIn: 'Back to sign in',
    newPassTitle: 'Choose a new password', newPassLede: 'Enter the new password for your account.', newPassSave: 'Save password',
    closeBtnReal: 'Delete my account', closeYesReal: 'Yes, delete my account', closeQReal: 'Delete your account and data for good?', closeBodyReal: 'Your name, number, email, photos, bank details and messages are deleted right away, and the account is closed with no way back. Projects, bids and agreements stay as records without a name. A project in progress has to be finished first.', closeDone: 'Your account and personal data are deleted. Thank you, and we hope to see you again.', erased: 'The account is erased.',
    otpTitle: 'Verify your mobile', otpLede: 'We sent a six-digit code by WhatsApp to', otpCode: 'Code', otpVerify: 'Confirm the code', otpResend: 'Send the code again', otpLater: 'Later', otpSent: 'The code is sent. It works for ten minutes.',
    newPassAgain: 'Repeat the password', resetDoneTitle: 'Your password is changed', resetDoneLede: 'You are signed in, and a confirmation email is on its way to you.', resetDoneGo: 'Open your dashboard',
    resetExpiredTitle: 'This link has expired', resetExpiredLede: 'A reset link works once, for a limited time. Request a new one from the sign-in page.', resetExpiredGo: 'Go to sign in',
    confirmSent: 'We sent a confirmation email. Open the link in it, then sign in.',
    err: {
      email: 'Enter a valid email address.', password: 'The password needs at least 8 characters.',
      pwned: 'This password has appeared in a data breach elsewhere, so it is not safe. Choose a different one.',
      name: 'Enter your full name.', mobile: 'Enter a valid mobile number, like 0551234567.', agree: 'Please accept the Terms and the Privacy Policy.',
      wrong: 'The email or password is not right.', exists: 'An account with this email already exists. Sign in instead.',
      mobileTaken: 'This mobile number belongs to another account. Sign in to it, or use a different number.', passwordMatch: 'The two passwords do not match.',
      caseReply: 'The reply could not be sent. Try again.', activeProject: 'You have a project in progress. Finish it, or contact the team first.', otpOff: 'Mobile verification is not switched on right now.', otpWrong: 'The code is wrong or has expired. Request a new one.',
      unconfirmed: 'Confirm your email from the message we sent, then sign in.', rate: 'Too many attempts. Wait a minute and try again.',
      network: 'Could not connect. Check your internet and try again.', generic: 'Something went wrong. Please try again.',
      waOff: 'WhatsApp updates are not switched on yet.', waLimit: 'You have reached today\'s limit of test messages. Try again tomorrow.', waNumber: 'Enter a Saudi mobile number, like 0551234567.',
      notHomeowner: 'Only homeowner accounts can post projects.', tooMany: 'You have 10 open projects. Close one before posting another.',
      title: 'Give the project a title (at least 3 characters).', desc: 'Describe the project in at least a sentence.', budget: 'Enter a valid budget: the minimum cannot exceed the maximum, and the maximum cannot exceed SAR 1,000,000.',
    },
    posted: 'Your project is posted. Tarmem\'s team reviews it and contacts you on your mobile within one working day.',
    postedNoBids: 'Your project is posted and verified contractors can see it now. Their bids appear here as they arrive, and you get an email with each one.',
    publish: 'Post project',
    contactSent: 'We have your message. We reply within one working day.', contactFailed: 'The message could not be sent. Please try again.',
    verifiedMessage: (person: string, company: string, link: string, hasAccount: boolean) => hasAccount
      ? `Hello ${person}, this is the Tarmem team.\n${company}'s account is verified and ready to use. Sign in with the email and password you created:\n${link}`
      : `Hello ${person}, this is the Tarmem team.\n${company}'s application is accepted. To finish, create your account on the contractor page:\n${link.replace('/signin', '/join')}`,
    coPendingTitle: 'Your account is being verified', coPendingNote: 'We have your application and your account is created. The Tarmem team reviews your details and contacts you on your mobile; you get an email the moment the account is live. Open projects then appear here.',
    choseNote: 'You chose the bid from {co}. The Tarmem team will contact you and the contractor to complete the agreement and start the work.', chosenNote: 'The homeowner chose your bid. The Tarmem team will contact you to complete the agreement and start the work.',
    paySoonTitle: 'Payment on the site is being set up', paySoonNote: 'Both sides have signed the agreement; it is saved with your names and the time of each signature. The Tarmem team will contact you both to arrange the first payment and start the work. Once payment on the site is live, payments are made here and released as each stage is approved.', refresh: 'Refresh',
    stagesAfterAward: 'Stages start once the project is awarded to a contractor.',
    stagesSoon: 'Stages start once the first payment is arranged. Approving stages and releasing their payments on the site goes live together with payment.',
    settingsMobileNote: 'Used to reach you, and for WhatsApp updates.', settingsEmail: 'Email (you sign in with it)',
    protectNoNafath: 'The Tarmem team reviews the business details and its commercial registration before the profile goes live.',
    postedNoBidsWa: 'Your project is posted and verified contractors can see it now. Their bids appear here as they arrive, and you get an email and a WhatsApp with each new bid.',
    msgsNoThread: 'Messaging with a contractor opens with the first bid on your project.', msgsEmpty: 'No messages yet. Write the first one; the other side is told by email and WhatsApp.', msgsWith: 'Conversation with', msgFailed: 'The message could not be sent. Try again.', msgsHomeowner: 'The homeowner', msgsContractor: 'The contractor',
    msgsSoon: 'Messaging inside the project is being set up. Until then the Tarmem team reaches you both by email and WhatsApp; the bids, the agreement and the files stay here.', msgsFrom: 'Tarmem',
    waSub: 'Tarmem sends your project updates to WhatsApp: new bids, an accepted bid, the signed agreement and stages. Each message has a button that opens the project.', waNumberNote: 'This is your account\'s mobile number; changing it here changes it on your account too.',
    waPreview: 'Status update for your project P-2001 on Tarmem: bid number 3 was received from Build Co, SAR 52,000, 30 days. The details are on the project page. [Open the project]',
    settingsSaved: 'Your settings are saved.', emailLocked: 'To change the email you sign in with, message the Tarmem team.', closeTopic: 'Account closure request', closeBody: 'The account holder asks for their account to be closed.',
    companyLocked: 'The company name is the one Tarmem verified and cannot be changed here. Put it back as it was; to change it, message the Tarmem team.', noWorkYet: 'No projects completed through Tarmem yet', noReviewsYet: 'No reviews yet',
    pfAdd: 'Add photos of your work', pfCaption: 'A short caption for the next photos (optional)', pfCaptionPh: 'e.g. Kitchen in Al Arid, 2026', pfHint: 'Up to 12 photos, JPG or PNG, 8 MB each. Homeowners comparing bids see them.', pfRemove: 'Remove', pfFull: 'You have reached the limit (12 photos). Remove one to add another.', pfFailed: 'The photo could not be uploaded. Try again.',
    wrTitle: 'Requests awaiting confirmation', wrNote: 'A request stays here until you have confirmed the money with the payment provider or the bank. Confirming records it in the person\'s wallet; rejecting cancels it.', wrNone: 'No requests are waiting.', wrDeposit: 'Deposit', wrPayout: 'Payout', wrConfirm: 'Confirm received', wrPaid: 'Mark as paid', wrReject: 'Reject',
    coRefresh: 'Check again', bidsSoonTitle: 'Bidding opens soon', bidsSoonNote: 'Your account is verified and you can browse open projects. Bidding on the site is about to launch; until then, message the Tarmem team about a project you want.',
    coPassword: 'Choose a password for your account', coEmailNeeded: 'Enter your email: you sign in with it once verified.', coCreate: 'Send application and create account',
    uploading: 'Uploading files…', uploadFailed: 'This file could not be uploaded. Try again from the Files tab.',
    fileErr: { type: 'Allowed files: JPG and PNG images, and PDF files.', size: 'A file can be 10 MB at most.', count: 'A project can hold 10 files at most.' },
    joinSent: 'We have your application. Tarmem\'s team will contact you to complete verification.', joinSend: 'Send application', inbox: 'Inbox', inboxOpen: 'Open the inbox: projects, applications, messages →',
  },
} as const;

export type PlatformLang = keyof typeof PLATFORM_COPY;
export type PlatformError = keyof typeof PLATFORM_COPY['en']['err'];
