/* Words the real-accounts pages need that the design does not have: it signs people in with a
   mobile code and Nafath, neither of which is connected yet, so the public site uses email and
   a password for now. Wording here is a first draft for the owner to review. */

export const PLATFORM_COPY = {
  ar: {
    notice: 'إطلاق مبكر: انشر مشروعك، واستقبل عروض مقاولين موثّقين، ووقّع الاتفاقية عبر الموقع. يوثّق فريق ترميم المقاولين يدويًا حاليًا، والدفع عبر الموقع قيد التفعيل.',
    // (033) shown to contractors, in small type after the notice, while example projects are listed
    samplesNote: 'بعض المشاريع المعروضة نماذج توضيحية خلال الإطلاق المبكر.',
    signInTitle: 'سجّل دخولك', signUpTitle: 'أنشئ حسابك',
    signInLede: 'ادخل ببريدك الإلكتروني وكلمة المرور لمتابعة مشاريعك.',
    signUpLede: 'حساب واحد لنشر مشاريعك ومتابعتها. يستغرق دقيقة.',
    pendingPost: 'مشروعك جاهز. أنشئ حسابك أو سجّل دخولك لننشره باسمك.',
    email: 'البريد الإلكتروني', password: 'كلمة المرور', passwordHint: '8 أحرف على الأقل',
    name: 'الاسم الكامل', mobile: 'رقم الجوال', mobilePh: '05XXXXXXXX', city: 'المدينة',
    agree: 'أوافق على', terms: 'شروط الاستخدام', and: 'و', privacy: 'سياسة الخصوصية',
    signIn: 'تسجيل الدخول', signUp: 'إنشاء الحساب', working: 'لحظة…',
    contractorNote: 'مقاول؟ التسجيل للمقاولين يتم عبر', contractorLink: 'طلب الانضمام',
    forgot: 'نسيت كلمة المرور؟', forgotLink: 'أعد تعيينها', forgotTitle: 'إعادة تعيين كلمة المرور', forgotLede: 'اكتب بريدك الإلكتروني ونرسل لك رابطًا لاختيار كلمة مرور جديدة.', forgotSend: 'أرسل الرابط',
    forgotSent: 'إذا كان هذا البريد مسجّلًا لدينا فستصلك رسالة خلال دقائق فيها رابط لاختيار كلمة مرور جديدة. تحقق من البريد غير المرغوب أيضًا.', backToSignIn: 'العودة لتسجيل الدخول',
    newPassTitle: 'اختر كلمة مرور جديدة', newPassLede: 'اكتب كلمة المرور الجديدة لحسابك.', newPassSave: 'حفظ كلمة المرور',
    closeBtnReal: 'حذف حسابي', closeYesReal: 'نعم، احذف حسابي', closeQReal: 'حذف حسابك وبياناتك نهائيًا؟', closeBodyReal: 'يُحذف اسمك ورقمك وبريدك وصورك وبياناتك البنكية ورسائلك فورًا، ويُغلق الحساب ولا يمكن استعادته. تبقى المشاريع والعطاءات والاتفاقيات سجلات بلا اسم، ومعها صور المشروع الذي أُسند ورسائله لأنها سجل العمل. مشروع جارٍ يجب إكماله أولًا.', closeDone: 'تم حذف حسابك وبياناتك الشخصية. شكرًا لك، ونتمنى أن نراك مجددًا.', erased: 'تم حذف الحساب.',
    otpTitle: 'وثّق رقم جوالك', otpLede: 'أرسلنا رمزًا من ستة أرقام عبر واتساب إلى', otpCode: 'الرمز', otpVerify: 'تأكيد الرمز', otpResend: 'أعد إرسال الرمز', otpLater: 'لاحقًا', otpSent: 'أُرسل الرمز. صالح لعشر دقائق.',
    newPassAgain: 'أعد كتابة كلمة المرور', resetDoneTitle: 'تم تغيير كلمة المرور', resetDoneLede: 'أنت الآن مسجّل الدخول، وستصلك رسالة تأكيد على بريدك.', resetDoneGo: 'افتح لوحتك',
    resetExpiredTitle: 'انتهت صلاحية هذا الرابط', resetExpiredLede: 'رابط إعادة التعيين يعمل مرة واحدة ولوقت محدود. اطلب رابطًا جديدًا من صفحة تسجيل الدخول.', resetExpiredGo: 'إلى تسجيل الدخول',
    confirmSent: 'أرسلنا رسالة تأكيد إلى بريدك. افتح الرابط الذي فيها ثم سجّل دخولك.',
    err: {
      email: 'اكتب بريدًا إلكترونيًا صحيحًا.', password: 'كلمة المرور 8 أحرف على الأقل.',
      pwned: 'كلمة المرور هذه ظهرت في تسريبات بيانات سابقة على الإنترنت، فهي غير آمنة. اختر كلمة مرور أخرى.',
      crLimits: 'بعد هذا التغيير تخرج قيمة المشروع عن حدودها (من 100 إلى 1,000,000 ريال).', crTooMany: 'على المشروع عشرة طلبات بانتظار الاعتماد. اعتمدوا بعضها أولًا.', crNotYet: 'تتاح طلبات التغيير بعد توقيع الطرفين للاتفاقية.',
      name: 'اكتب اسمك الكامل (حرفان على الأقل).', mobile: 'اكتب رقم جوال سعوديًا صحيحًا، مثل 0551234567.', agree: 'يلزم قبول الشروط وسياسة الخصوصية.',
      wrong: 'البريد أو كلمة المرور غير صحيحة.', exists: 'يوجد حساب بهذا البريد. سجّل دخولك بدلًا من ذلك.',
      mobileTaken: 'رقم الجوال هذا مسجّل لحساب آخر. سجّل الدخول إليه، أو استخدم رقمًا آخر.', passwordMatch: 'كلمتا المرور غير متطابقتين.',
      caseReply: 'تعذّر إرسال الرد. حاول مرة أخرى.', activeProject: 'لديك مشروع جارٍ. أكمله أو تواصل مع الفريق أولًا.', otpOff: 'توثيق الجوال غير مفعّل حاليًا.', otpWrong: 'الرمز غير صحيح أو انتهت صلاحيته. اطلب رمزًا جديدًا.',
      verifyFirst: 'أكّد بريدك الإلكتروني أولًا من الرابط الذي أرسلناه إليك، ثم تستطيع ذلك.',
      exampleProject: 'هذا مشروع توضيحي: لا يُسحب من هنا، لأن سحبه يرسل رسالة لكل من قدّم عليه. تُزال الأمثلة بهدوء من Supabase بالأمر preview_clear.',
      tsWrong: 'الرمز غير صحيح أو انتهت صلاحيته. اكتب الرمز الظاهر الآن في التطبيق.', tsFailed: 'تعذّر بدء إعداد التحقق بخطوتين الآن. حاول مرة أخرى بعد قليل.',
      unconfirmed: 'فعّل حسابك أولًا من الرابط الذي أرسلناه إلى بريدك، ثم سجّل دخولك.', rate: 'محاولات كثيرة. انتظر دقيقة ثم حاول مجددًا.',
      rateHour: 'وصلت إلى الحد المسموح خلال ساعة. حاول مجددًا لاحقًا، أو راسلنا عبر واتساب.', rateNow: 'الطلبات كثيرة الآن. حاول مجددًا بعد دقائق.',
      session: 'انتهت جلستك. سجّل دخولك مجددًا لتكمل من حيث توقفت.',
      network: 'تعذّر الاتصال. تحقق من الإنترنت وحاول مجددًا.', generic: 'حدث خطأ غير متوقع. حاول مجددًا.',
      waOff: 'تحديثات واتساب لم تُفعَّل بعد.', waLimit: 'وصلت إلى الحد اليومي للرسائل التجريبية. جرّب غدًا.', waNumber: 'اكتب رقم جوال سعودي، مثل 0551234567.',
      waVerify: 'وثّق رقم جوالك برمز واتساب أولًا، ثم أرسل الرسالة التجريبية.',
      notHomeowner: 'نشر المشاريع متاح لحسابات أصحاب المنازل فقط.', tooMany: 'لديك 10 مشاريع مفتوحة. أغلق أحدها قبل نشر مشروع جديد.',
      title: 'اكتب عنوانًا للمشروع من 3 إلى 140 حرفًا.', desc: 'صف المشروع في 10 أحرف على الأقل (حتى 4,000 حرف).', budget: 'اكتب ميزانية صحيحة: الحد الأدنى لا يتجاوز الأعلى، والأعلى لا يتجاوز 1,000,000 ريال.',
      district: 'اسم الحي أطول من المسموح (120 حرفًا).',
      bidPrice: 'اكتب سعرًا بين 100 و1,000,000 ريال.', bidDays: 'اكتب مدة بين يوم واحد و1,000 يوم.', noteLong: 'الملاحظة أطول من المسموح (2,000 حرف). اختصرها قليلًا.', bidDetails: 'تفاصيل العرض أطول من المسموح. اختصر ما يشمله العرض وما لا يشمله.',
      notOpen: 'هذا المشروع لم يعد مفتوحًا للعروض، فلا يمكن إتمام هذه الخطوة.', bidGone: 'لم يعد هذا العرض متاحًا للتوقيع. حدّث الصفحة وراجع العروض.', signedAlready: 'وقّع الطرفان هذه الاتفاقية من قبل.',
      contactName: 'اكتب اسمك (حرفان على الأقل).', contactReach: 'اترك بريدًا إلكترونيًا أو رقم جوال لنرد عليك.', contactPhone: 'اكتب رقم جوال صحيحًا، مثل 0551234567، أو اتركه فارغًا واكتب بريدك.', contactMsg: 'اكتب رسالتك من 3 أحرف إلى 4,000 حرف.',
      company: 'اكتب اسم المنشأة (من حرفين إلى 160 حرفًا).', person: 'اكتب اسم المسؤول (من حرفين إلى 120 حرفًا).', cr: 'رقم السجل التجاري أرقام فقط، من 5 إلى 15 رقمًا.', trades: 'اختر تخصصًا واحدًا على الأقل.',
      msgLong: 'الرسالة أطول من المسموح (2,000 حرف).', reviewText: 'اكتب تقييمك من 3 أحرف إلى 1,200 حرف.', reviewStars: 'اختر عدد النجوم.',
      cannotComplete: 'لا يمكن تأكيد الإنجاز الآن: يلزم أن يكون المشروع قيد التنفيذ وموقّعًا من الطرفين.', notYours: 'هذه الخطوة ليست متاحة لحسابك.',
      statusNotAllowed: 'تغيّرت حالة المشروع ولم تعد تسمح بهذه الخطوة. حدّث الصفحة.', adminsOnly: 'هذه الخطوة لفريق ترميم فقط.',
    },
    posted: 'نُشر مشروعك. يراجعه فريق ترميم ويتواصل معك على جوالك خلال يوم عمل.',
    postedNoBids: 'نُشر مشروعك ويراه المقاولون الموثّقون الآن. تظهر عروضهم هنا فور وصولها، ويصلك بريد مع كل عرض جديد.',
    publish: 'نشر المشروع',
    contactSent: 'وصلتنا رسالتك. نرد عليك خلال يوم عمل.', contactFailed: 'تعذّر إرسال الرسالة. حاول مجددًا.',
    verifiedMessage: (person: string, company: string, link: string, hasAccount: boolean) => hasAccount
      ? `مرحبًا ${person}، معك فريق ترميم.\nتم توثيق حساب «${company}» وأصبح جاهزًا للاستخدام. سجّل دخولك بالبريد وكلمة المرور اللذين أنشأتهما:\n${link}`
      : `مرحبًا ${person}، معك فريق ترميم.\nتم قبول طلب «${company}». لإكمال التسجيل أنشئ حسابك من صفحة انضمام المقاولين:\n${link.replace('/signin', '/join')}`,
    coPendingTitle: 'حسابك قيد التوثيق', coPendingNote: 'استلمنا طلبك وأنشأنا حسابك. يراجع فريق ترميم بياناتك ويتواصل معك على جوالك، وتصلك رسالة على بريدك فور تفعيل الحساب. بعدها تظهر لك المشاريع المفتوحة هنا.',
    choseNote: 'اخترت عرض «{co}». يتواصل فريق ترميم معك ومع المقاول لإتمام الاتفاقية وبدء العمل.', chosenNote: 'اختار صاحب المنزل عرضك. يتواصل معك فريق ترميم لإتمام الاتفاقية وبدء العمل.',
    nextArrange: 'يتواصل معكما فريق ترميم لترتيب الدفعة الأولى وبدء العمل، والتفاصيل في تبويب الدفعات.',
    paySoonTitle: 'الدفع عبر الموقع قيد التفعيل', paySoonNote: 'وقّع الطرفان الاتفاقية، وهي محفوظة باسميكما وتاريخ التوقيع. يتواصل فريق ترميم معكما لترتيب الدفعة الأولى وبدء العمل. عند تفعيل الدفع عبر الموقع تُودَع الدفعات هنا وتُصرف مع اعتماد كل مرحلة.', refresh: 'تحقّق من حالة الدفع',
    paySoonNoteCo: 'الدفع عبر الموقع قيد التفعيل. يتواصل معك فريق ترميم لترتيب الدفعات، وتظهر مستحقاتك هنا بعد التفعيل.', payStillOff: 'الدفع عبر الموقع لم يُفعَّل بعد. يتواصل معكما فريق ترميم لترتيب الدفعات.',
    stagesAfterAward: 'تبدأ المراحل بعد إسناد المشروع إلى مقاول.',
    stagesSoon: 'تبدأ المراحل بعد ترتيب الدفعة الأولى. اعتماد المراحل وصرف دفعاتها عبر الموقع يُفعَّل مع الدفع.',
    settingsMobileNote: 'يُستخدم للتواصل معك ولرسائل واتساب.', settingsEmail: 'البريد الإلكتروني (لتسجيل الدخول)',
    protectNoNafath: 'يراجع فريق ترميم بيانات المنشأة وسجلها التجاري قبل ظهور الملف.',
    postedNoBidsWa: 'نُشر مشروعك ويراه المقاولون الموثّقون الآن. تظهر عروضهم هنا فور وصولها، ويصلك بريد ورسالة واتساب مع كل عرض جديد.',
    msgsNoThread: 'تفتح المراسلة مع المقاول عند وصول أول عطاء على مشروعك.', msgsEmpty: 'لا رسائل بعد. اكتب أول رسالة، ويصل الطرف الآخر تنبيه بالبريد وواتساب.', msgsWith: 'المحادثة مع', msgFailed: 'تعذّر إرسال الرسالة. حاول مجددًا.', msgsHomeowner: 'صاحب المنزل', msgsContractor: 'المقاول',
    msgsSoon: 'المراسلة داخل المشروع قيد التفعيل. حتى ذلك الحين يتواصل معكما فريق ترميم بالبريد وواتساب، وتبقى العروض والاتفاقية والملفات هنا.', msgsFrom: 'ترميم',
    waSub: 'ترسل ترميم تحديثات مشروعك إلى واتساب: العروض الجديدة، وقبول العرض، وتوقيع الاتفاقية، والمراحل. في كل رسالة زر يفتح المشروع مباشرة.', waNumberNote: 'هذا رقم جوال حسابك؛ تغييره هنا يغيّره في حسابك أيضًا.',
    waPreview: 'تحديث حالة مشروعك رقم P-2001 في ترميم: تم استلام العطاء رقم 3 من مؤسسة البناء المتقن بقيمة 52,000 ريال ومدة تنفيذ 30 يوم. التفاصيل في صفحة المشروع. [افتح المشروع]',
    settingsSaved: 'حُفظت إعداداتك.', emailLocked: 'لتغيير بريد تسجيل الدخول راسل فريق ترميم.', closeTopic: 'طلب إغلاق الحساب', closeBody: 'يطلب صاحب الحساب إغلاق حسابه.',
    companyLocked: 'اسم المنشأة هو الاسم الموثّق لدى ترميم ولا يُغيَّر من هنا. أعده كما كان، ولتغييره راسل فريق ترميم.', noWorkYet: 'لا مشاريع مكتملة عبر ترميم بعد', noReviewsYet: 'لا تقييمات بعد',
    pfAdd: 'أضف صورًا من أعمالك', pfCaption: 'وصف قصير للصور التالية (اختياري)', pfCaptionPh: 'مثال: مطبخ في حي العارض، 2026', pfHint: 'حتى 12 صورة، JPG أو PNG، 8 ميغابايت للصورة. تظهر لأصحاب المنازل الذين يقارنون العروض.', pfRemove: 'حذف', pfFull: 'وصلت إلى الحد الأقصى (12 صورة). احذف صورة لتضيف أخرى.', pfFailed: 'تعذّر رفع الصورة. حاول مجددًا.',
    wrTitle: 'طلبات بانتظار التأكيد', wrNote: 'يبقى الطلب هنا حتى تتأكد من وصول المبلغ عند مزود الدفع أو البنك. التأكيد يُثبت المبلغ في محفظة صاحبه؛ الرفض يلغيه.', wrNone: 'لا طلبات بانتظار التأكيد.', wrDeposit: 'إيداع', wrPayout: 'تحويل', wrConfirm: 'تأكيد الوصول', wrPaid: 'تم التحويل', wrReject: 'رفض',
    coRefresh: 'تحديث الحالة', bidsSoonTitle: 'تقديم العروض يفتح قريبًا', bidsSoonNote: 'حسابك موثّق ويمكنك تصفّح المشاريع المفتوحة. تقديم العروض من الموقع قيد الإطلاق؛ إلى ذلك الحين راسل فريق ترميم بشأن المشروع الذي يهمّك.',
    coPassword: 'اختر كلمة مرور لحسابك', coEmailNeeded: 'اكتب بريدك الإلكتروني: به تسجّل دخولك بعد التوثيق.', coCreate: 'إرسال الطلب وإنشاء الحساب',
    uploading: 'جارٍ رفع الملفات…', uploadFailed: 'تعذّر رفع هذا الملف. حاول مجددًا من تبويب الملفات.',
    fileErr: { type: 'الملفات المسموحة: صور JPG وPNG وملفات PDF.', size: 'الحد الأقصى لحجم الملف 10 ميغابايت.', count: 'الحد الأقصى 10 ملفات للمشروع.' },
    joinSent: 'وصلنا طلبك. يتواصل معك فريق ترميم لاستكمال التوثيق.', joinSend: 'إرسال الطلب', inbox: 'الوارد', inboxOpen: 'افتح الوارد: المشاريع والطلبات والرسائل ←',
    // email confirmation (supabase/030 F): the account opens from the link in the email
    confirmTitle: 'فعّل حسابك من الرابط في بريدك',
    confirmLede: (email: string) => `أرسلنا رابط التفعيل إلى ${email}. افتحه لتفعيل حسابك وتسجيل دخولك، ولو من جهاز آخر. إن لم تجد الرسالة فتحقق من البريد غير المرغوب.`,
    confirmDraft: 'مشروعك محفوظ على هذا الجهاز، ويُنشر تلقائيًا بعد تفعيل حسابك وتسجيل دخولك منه.',
    confirmCo: 'وصلنا طلبك. بعد تفعيل حسابك يراجع فريق ترميم بياناتك ويتواصل معك على جوالك.',
    // (031) explore first, verify before dealing: the banner for an account that cannot deal yet, and what the link says
    verifyBarHo: (email: string) => `أكّد بريدك الإلكتروني ليظهر مشروعك للمقاولين وتستطيع مراسلتهم واعتماد العروض. أرسلنا رابط التأكيد إلى ${email}.`,
    verifyBarCo: (email: string) => `أكّد بريدك الإلكتروني لتستطيع تقديم العروض ومراسلة أصحاب المنازل. أرسلنا رابط التأكيد إلى ${email}.`,
    verifyBarProfile: 'أكمل بيانات حسابك من الإعدادات (الاسم ورقم الجوال) لتبدأ التعامل عبر ترميم.',
    verifyBarOtp: 'أكّد رقم جوالك من الإعدادات لتبدأ التعامل عبر ترميم.',
    verifyResend: 'أعد إرسال الرابط', verifyCheck: 'أكّدت بريدي', verifySettings: 'الإعدادات',
    verifySent: 'أرسلنا رابطًا جديدًا. تحقّق من بريدك، ومن مجلد الرسائل غير المرغوبة.',
    verifyRate: 'أرسلنا عدة روابط خلال الساعة الماضية. انتظر قليلًا ثم حاول مجددًا.',
    verifyNotYet: 'لم يُؤكَّد بريدك بعد. افتح الرابط الذي أرسلناه إليك.',
    verifiedNow: 'تم تأكيد بريدك الإلكتروني. حسابك جاهز للتعامل الآن.',
    verifiedSignIn: 'تم تأكيد بريدك الإلكتروني. سجّل دخولك للمتابعة.',
    verifyExpired: 'انتهت صلاحية رابط التأكيد. سجّل دخولك واطلب رابطًا جديدًا من الشريط أعلى الصفحة.',
    verifyInvalid: 'رابط التأكيد غير صالح. سجّل دخولك واطلب رابطًا جديدًا من الشريط أعلى الصفحة.',
    postedHeld: 'حفظنا مشروعك، ولن يظهر للمقاولين قبل أن تؤكد بريدك الإلكتروني من الرابط الذي أرسلناه إليك. بعد التأكيد يظهر لهم تلقائيًا.',
    // (032) the team's second step: a code from an authenticator app after the password, before the console opens
    tsSetupTitle: 'فعّل التحقق بخطوتين للوحة الإدارة',
    tsSetupLede: 'لحماية لوحة الإدارة، نطلب بعد كلمة المرور رمزًا من تطبيق مصادقة على جوالك. تُعِدّه مرة واحدة.',
    tsStep1: 'ثبّت تطبيق مصادقة على جوالك، مثل Google Authenticator أو Microsoft Authenticator.',
    tsStep2: 'في التطبيق اختر «إضافة حساب»، ثم امسح هذا الرمز.',
    tsStep3: 'اكتب الرمز المكوّن من ستة أرقام الذي يظهر في التطبيق.',
    tsQrAlt: 'رمز QR لإضافة ترميم إلى تطبيق المصادقة', tsNoScan: 'لا تستطيع المسح؟ أدخل هذا المفتاح في التطبيق بدلًا منه:',
    tsCopy: 'نسخ المفتاح', tsCopied: 'تم النسخ', tsLoading: 'نجهّز رمز الإعداد…', tsRetry: 'حاول مرة أخرى',
    tsCode: 'الرمز من التطبيق', tsTurnOn: 'تفعيل ومتابعة',
    tsTitle: 'التحقق بخطوتين', tsLede: 'اكتب الرمز المكوّن من ستة أرقام الظاهر الآن في تطبيق المصادقة على جوالك.', tsContinue: 'متابعة',
    tsSignOut: 'تسجيل الخروج',
    tsLost: 'فقدت جوالك؟ يُزال التحقق بخطوتين من لوحة Supabase (Authentication ثم Users، ثم الحساب، ثم Remove MFA factors)، ثم تُعِدّه هنا من جديد عند الدخول.',
    tsDone: 'تم تفعيل التحقق بخطوتين. ستطلب لوحة الإدارة رمزًا من التطبيق عند كل تسجيل دخول.',
    resend: 'أعد إرسال الرابط', resent: 'أرسلنا الرابط مرة أخرى. قد يستغرق وصوله دقيقة.', confirmedWelcome: 'تم تفعيل حسابك. أهلًا بك في ترميم.',
    linkExpiredTitle: 'انتهت صلاحية الرابط أو استُخدم من قبل', linkExpiredLede: 'روابط التفعيل وإعادة التعيين تعمل مرة واحدة ولوقت محدود. اكتب بريدك ونرسل لك رابطًا جديدًا.',
    linkSendSignup: 'أرسل رابط تفعيل جديدًا', linkSendReset: 'أرسل رابط إعادة تعيين جديدًا', linkOr: 'أو',
    linkSentSignup: 'إذا كان الحساب بانتظار التفعيل فسيصلك رابط جديد خلال دقائق. تحقق من البريد غير المرغوب أيضًا.',
    draftPhotos: 'نُشر مشروعك. الصور التي اخترتها قبل تفعيل الحساب لم تُحفظ على الجهاز، فأضفها من تبويب الملفات في صفحة المشروع.',
    notHomeownerPost: 'حسابات المقاولين لا تنشر مشاريع. لطلب ترميم لمنزلك أنشئ حساب صاحب منزل ببريد آخر.',
    // one wording for a signed project while payment on the site is off
    signedArrange: 'موقّع · يرتّب فريق ترميم البدء', statusOpen: 'مفتوح للعروض', statusCompleted: 'مكتمل', statusWithdrawn: 'مسحوب',
    msgsNoThreadCo: 'تفتح المراسلة مع صاحب المنزل بعد تقديم عرضك.',
    nextCta: { bids: 'قارن العروض', bid: 'قدّم عرضك', agreement: 'راجع الاتفاقية', messages: 'افتح الرسائل', stages: 'افتح المراحل', payments: 'افتح الدفعات', review: 'قيّم المقاول', complete: 'تأكيد إنجاز العمل', files: 'أضف الصور' },
    nextSignedHo: 'يتواصل معكما فريق ترميم لترتيب البدء. تابع التفاصيل مع المقاول في الرسائل، وأكّد إنجاز العمل هنا عند اكتماله.',
    nextSignedCo: 'يتواصل معكما فريق ترميم لترتيب البدء. نسّق التفاصيل مع صاحب المنزل في الرسائل، وأكّد إنجاز العمل هنا عند اكتماله.',
    nextPendingHo: 'وقّعت الاتفاقية، وهي بانتظار توقيع المقاول. يصلك إشعار فور توقيعه.',
    nextPendingCo: 'اختار صاحب المنزل عرضك ووقّع الاتفاقية. راجعها ووقّعها ليُسند المشروع إليك.',
    nextDoneHo: 'اكتمل المشروع. شاركنا تقييمك للمقاول.', nextDoneCo: 'اكتمل المشروع. شكرًا لعملك مع ترميم.', nextReviewed: 'اكتمل المشروع، وشكرًا على تقييمك.',
    stagesPlanned: 'تبدأ المراحل بعد ترتيب الدفعة الأولى',
    // the accepted bid, read-only, and the stages it plans (while payment on the site is off)
    acceptedTitle: 'العرض المعتمد', acceptedChosen: 'اخترته ووُقّعت الاتفاقية عليه', acceptedChosenCo: 'اختاره صاحب المنزل ووُقّعت الاتفاقية عليه', acceptedSplit: 'تقسيم الدفعات على المراحل', acceptedVat: 'المقاول مسجّل في ضريبة القيمة المضافة، فتُضاف الضريبة (15%) إلى هذه القيمة', acceptedVisit: 'يشمل زيارة معاينة قبل البدء',
    plannedTitle: 'المراحل المخططة', plannedNote: 'تبدأ المراحل بعد ترتيب الدفعة الأولى مع فريق ترميم. اعتماد المراحل وصرف دفعاتها عبر الموقع يُفعَّل مع الدفع.', plannedWaiting: 'مخططة',
    // each party confirms the work is finished while payment on the site is off; the project completes once both have (supabase/030 B)
    completeTitle: 'هل انتهى العمل؟', completeNote: 'عندما يُنهي المقاول العمل المتفق عليه أكّد ذلك هنا. يُسجَّل المشروع مكتملًا حين يؤكده المقاول أيضًا، ويُفتح لك تقييمه.',
    completeTitleCo: 'هل أنهيت العمل؟', completeNoteCo: 'عندما تُنهي العمل المتفق عليه أكّد ذلك هنا، فيُطلب من صاحب المنزل مراجعته وتأكيده. يُسجَّل المشروع مكتملًا حين يؤكده الطرفان.',
    completeBtn: 'تأكيد إنجاز العمل', completeQ: 'تأكيد أن العمل اكتمل؟ لا يمكن التراجع عن هذه الخطوة.', completeYes: 'نعم، اكتمل العمل', completeNo: 'ليس بعد',
    completeWaitHo: 'سجّلنا تأكيدك لإنجاز العمل، وننتظر تأكيد المقاول. يُسجَّل المشروع مكتملًا فور تأكيده.',
    completeWaitCo: 'سجّلنا تأكيدك لإنجاز العمل، وننتظر مراجعة صاحب المنزل وتأكيده. يُسجَّل المشروع مكتملًا فور تأكيده.',
    completeAskHo: 'أكّد المقاول إنجاز العمل. راجعه، فإن كان مكتملًا فأكّد ذلك هنا ليُسجَّل المشروع مكتملًا ويُفتح لك تقييم المقاول. وإن بقي شيء فراسله من تبويب الرسائل.',
    completeAskCo: 'أكّد صاحب المنزل إنجاز العمل. أكّده أنت أيضًا ليُسجَّل المشروع مكتملًا.',
    completeWaitTagHo: 'بانتظار تأكيد المقاول', completeWaitTagCo: 'بانتظار تأكيد صاحب المنزل', completeTheirsHo: 'أكّده المقاول', completeTheirsCo: 'أكّده صاحب المنزل',
    completeSent: 'سجّلنا تأكيدك، وأبلغنا الطرف الآخر ليؤكد بدوره.',
    completeDone: 'سُجّل المشروع مكتملًا. شاركنا تقييمك للمقاول.', completeDoneCo: 'سُجّل المشروع مكتملًا. شكرًا لعملك مع ترميم.',
    // a contractor whose application the team declined (supabase/030 E6)
    coDeclinedTitle: 'لم تتم الموافقة على طلبك', coDeclinedNote: 'راجع فريق ترميم طلب انضمامك ولم تتم الموافقة عليه. إن كان لديك سؤال أو معلومات جديدة عن منشأتك، راسلنا وسنعيد النظر فيه.', coDeclinedContact: 'تواصل مع فريق ترميم',
    // the team's console (supabase/030): labels in the page's language, and the team's controls on a project
    admPayOffCodes: 'الدفع عبر الموقع غير مفعّل بعد: الأكواد تُحفظ وتُدار هنا، ويبدأ استخدامها عند تفعيله.',
    admPayOffPartners: 'نقرات روابط الشركاء وتسجيلاتهم لا تُحتسب بعد، لذا تظهر أرقامها «—» حتى تفعيل الدفع عبر الموقع.',
    admPayOffLate: 'يُسجَّل التأخير والاسترداد هنا عند بدء الدفعات المرحلية عبر الموقع؛ لا شيء مسجّل حتى الآن.',
    admSender: 'المرسل', admNoApplication: 'بلا طلب توثيق', admPreview: 'تجريبي', admApp: { new: 'جديد', contacted: 'تم التواصل', verified: 'موثّق', declined: 'مرفوض' } as Record<string, string>,
    admSar: 'ريال', admCr: 'السجل التجاري', admDays: 'يومًا', admChosen: 'اختاره العميل',
    adminCtlTitle: 'إجراءات فريق ترميم',
    adminCtlOpen: 'المشروع مفتوح للعروض. أزِله إن كان مكررًا أو مزعجًا أو مخالفًا للقواعد: يُسحب من الموقع، ويُبلَّغ صاحبه ومن قدّم عليه عرضًا بالبريد.',
    adminCtlActive: 'المشروع موقّع وجارٍ. سجّله مكتملًا عند تسليم العمل، أو ألغِه إن توقّف العمل. يُبلَّغ الطرفان بالبريد في الحالتين.',
    adminComplete: 'تسجيل المشروع مكتملًا', adminCompleteQ: 'تسجيل المشروع مكتملًا؟ يُفتح لصاحب المنزل تقييم المقاول، ولا يمكن التراجع.', adminCompleteYes: 'نعم، سجّله مكتملًا', adminCompleted: 'سُجّل المشروع مكتملًا، وأُبلغ الطرفان بالبريد.',
    adminCancel: 'إلغاء المشروع', adminCancelQ: 'إلغاء المشروع؟ يُسجَّل مسحوبًا ولا يُستكمل عبر الموقع، ولا يمكن التراجع.', adminCancelYes: 'نعم، ألغِ المشروع', adminCancelled: 'أُلغي المشروع، وأُبلغ الطرفان بالبريد.',
    adminRemove: 'إزالة المشروع', adminRemoveQ: 'إزالة المشروع من الموقع؟ لا يعود مفتوحًا للعروض، ولا يمكن التراجع.', adminRemoveYes: 'نعم، أزِله', adminRemoved: 'أُزيل المشروع، وأُبلغ صاحبه ومن قدّم عليه عرضًا بالبريد.',
    adminKeep: 'تراجع', adminNoteLabel: 'ملاحظة داخلية (اختيارية)', adminNotePh: 'السبب، لسجل الفريق فقط. لا تُرسل لأحد.',
    msgsAdminRead: 'تقرأ هذه المحادثة للاطلاع فقط: لا تُرسل منها، ولا تُعلَّم الرسائل مقروءة لأحد.', msgsNoneYet: 'لا رسائل في هذا المشروع بعد.',
    // settings
    prefsCo: { pNewProjects: 'مشاريع جديدة في تخصصاتي (قريبًا)', pBidChosen: 'اختيار عرضي وتوقيع الاتفاقية', pMsg: 'الرسائل الجديدة', pChanges: 'طلبات التغيير' },
    pwTitle: 'كلمة المرور', pwNote: 'غيّر كلمة المرور التي تسجّل بها دخولك. تبقى مسجّل الدخول هنا، وتُسجَّل أجهزتك الأخرى خروجًا.', pwChange: 'تغيير كلمة المرور', pwSave: 'حفظ كلمة المرور', pwSaved: 'تم تغيير كلمة المرور، وسُجّلت أجهزتك الأخرى خروجًا.', pwCancel: 'إلغاء',
    emailReadOnly: 'بريد تسجيل الدخول لا يُغيَّر من هنا. لتغييره راسل فريق ترميم.',
    // what could not be done, said instead of undone silently
    withdrawFailed: 'تعذّر سحب المشروع، وما زال منشورًا. حاول مجددًا.', reviewFailed: 'تعذّر حفظ تقييمك. حاول مجددًا.', saveFailed: 'تعذّر حفظ المقاول في قائمتك. حاول مجددًا.',
    signFailed: 'تعذّر حفظ توقيعك.', filesRefused: 'لم يُرفع', filesEmpty: 'لا ملفات بعد.',
    pfType: 'الصور المسموحة: JPG وPNG وWebP.', pfSize: 'حجم الصورة 8 ميغابايت على الأكثر.',
    chars: (n: number, max: number) => `${n.toLocaleString('en-US')} / ${max.toLocaleString('en-US')}`,
  },
  en: {
    notice: 'Early access: post your project, receive bids from verified contractors, and sign the agreement on the site. The Tarmem team verifies contractors by hand for now, and payment on the site is being set up.',
    samplesNote: 'Some projects shown are examples during early access.',
    signInTitle: 'Sign in', signUpTitle: 'Create your account',
    signInLede: 'Use your email and password to follow your projects.',
    signUpLede: 'One account to post and follow your projects. It takes a minute.',
    pendingPost: 'Your project is ready. Create an account or sign in and we will post it under your name.',
    email: 'Email', password: 'Password', passwordHint: 'At least 8 characters',
    name: 'Full name', mobile: 'Mobile number', mobilePh: '05XXXXXXXX', city: 'City',
    agree: 'I agree to the', terms: 'Terms of use', and: 'and the', privacy: 'Privacy policy',
    signIn: 'Sign in', signUp: 'Create account', working: 'One moment…',
    contractorNote: 'A contractor? Contractors join through the', contractorLink: 'application form',
    forgot: 'Forgot your password?', forgotLink: 'Reset it', forgotTitle: 'Reset your password', forgotLede: 'Enter your email and we will send you a link to choose a new password.', forgotSend: 'Send the link',
    forgotSent: 'If this email has an account, a message with a link to choose a new password arrives within minutes. Check your spam folder too.', backToSignIn: 'Back to sign in',
    newPassTitle: 'Choose a new password', newPassLede: 'Enter the new password for your account.', newPassSave: 'Save password',
    closeBtnReal: 'Delete my account', closeYesReal: 'Yes, delete my account', closeQReal: 'Delete your account and data for good?', closeBodyReal: 'Your name, number, email, photos, bank details and messages are deleted right away, and the account is closed with no way back. Projects, bids and agreements stay as records without a name, and so do the photos and messages of a project that was awarded, as the record of the work. A project in progress has to be finished first.', closeDone: 'Your account and personal data are deleted. Thank you, and we hope to see you again.', erased: 'The account is erased.',
    otpTitle: 'Verify your mobile', otpLede: 'We sent a six-digit code by WhatsApp to', otpCode: 'Code', otpVerify: 'Confirm the code', otpResend: 'Send the code again', otpLater: 'Later', otpSent: 'The code is sent. It works for ten minutes.',
    newPassAgain: 'Repeat the password', resetDoneTitle: 'Your password is changed', resetDoneLede: 'You are signed in, and a confirmation email is on its way to you.', resetDoneGo: 'Open your dashboard',
    resetExpiredTitle: 'This link has expired', resetExpiredLede: 'A reset link works once, for a limited time. Request a new one from the sign-in page.', resetExpiredGo: 'Go to sign in',
    confirmSent: 'We sent a confirmation email. Open the link in it, then sign in.',
    err: {
      email: 'Enter a valid email address.', password: 'The password needs at least 8 characters.',
      pwned: 'This password has appeared in a data breach elsewhere, so it is not safe. Choose a different one.',
      crLimits: 'After this change the project’s value would leave its limits (100 to 1,000,000 riyals).', crTooMany: 'Ten change requests are already waiting on this project. Approve some first.', crNotYet: 'Change requests open once both parties have signed the agreement.',
      name: 'Enter your full name (at least 2 characters).', mobile: 'Enter a valid Saudi mobile number, like 0551234567.', agree: 'Please accept the Terms and the Privacy Policy.',
      wrong: 'The email or password is not right.', exists: 'An account with this email already exists. Sign in instead.',
      mobileTaken: 'This mobile number belongs to another account. Sign in to it, or use a different number.', passwordMatch: 'The two passwords do not match.',
      caseReply: 'The reply could not be sent. Try again.', activeProject: 'You have a project in progress. Finish it, or contact the team first.', otpOff: 'Mobile verification is not switched on right now.', otpWrong: 'The code is wrong or has expired. Request a new one.',
      verifyFirst: 'Confirm your email first with the link we sent you, then you can do this.',
      exampleProject: 'This is an example project: it is not withdrawn from here, because a withdrawal emails everyone who bid. Examples are removed quietly in Supabase with preview_clear.',
      tsWrong: 'That code is wrong or has expired. Type the code the app shows now.', tsFailed: 'Two-step set-up could not start right now. Try again in a moment.',
      unconfirmed: 'Activate your account first with the link we emailed you, then sign in.', rate: 'Too many attempts. Wait a minute and try again.',
      rateHour: 'You have reached the hourly limit. Try again later, or message us on WhatsApp.', rateNow: 'We are receiving a lot right now. Try again in a few minutes.',
      session: 'Your session ended. Sign in again to pick up where you left off.',
      network: 'Could not connect. Check your internet and try again.', generic: 'Something went wrong. Please try again.',
      waOff: 'WhatsApp updates are not switched on yet.', waLimit: 'You have reached today\'s limit of test messages. Try again tomorrow.', waNumber: 'Enter a Saudi mobile number, like 0551234567.',
      waVerify: 'Verify your mobile number with the WhatsApp code first, then send the test message.',
      notHomeowner: 'Only homeowner accounts can post projects.', tooMany: 'You have 10 open projects. Close one before posting another.',
      title: 'Give the project a title of 3 to 140 characters.', desc: 'Describe the project in at least 10 characters (up to 4,000).', budget: 'Enter a valid budget: the minimum cannot exceed the maximum, and the maximum cannot exceed SAR 1,000,000.',
      district: 'The district is longer than allowed (120 characters).',
      bidPrice: 'Enter a price between SAR 100 and 1,000,000.', bidDays: 'Enter a duration between 1 and 1,000 days.', noteLong: 'The note is longer than allowed (2,000 characters). Shorten it a little.', bidDetails: 'The bid details are too long. Shorten what the bid includes and excludes.',
      notOpen: 'This project is no longer open for bids, so this step cannot be completed.', bidGone: 'This bid is no longer available to sign. Refresh the page and review the bids.', signedAlready: 'Both parties have already signed this agreement.',
      contactName: 'Enter your name (at least 2 characters).', contactReach: 'Leave an email or a mobile number so we can reply.', contactPhone: 'Enter a valid mobile number, like 0551234567, or leave it empty and give your email.', contactMsg: 'Write your message in 3 to 4,000 characters.',
      company: 'Enter the company name (2 to 160 characters).', person: 'Enter the contact person\'s name (2 to 120 characters).', cr: 'The CR number is digits only, 5 to 15 of them.', trades: 'Choose at least one trade.',
      msgLong: 'The message is longer than allowed (2,000 characters).', reviewText: 'Write your review in 3 to 1,200 characters.', reviewStars: 'Choose a number of stars.',
      cannotComplete: 'The work cannot be confirmed yet: the project must be in progress and signed by both parties.', notYours: 'This step is not available to your account.',
      statusNotAllowed: 'The project\'s status has changed and no longer allows this step. Refresh the page.', adminsOnly: 'Only the Tarmem team can do this.',
    },
    posted: 'Your project is posted. Tarmem\'s team reviews it and contacts you on your mobile within one working day.',
    postedNoBids: 'Your project is posted and verified contractors can see it now. Their bids appear here as they arrive, and you get an email with each one.',
    publish: 'Post project',
    contactSent: 'We have your message. We reply within one working day.', contactFailed: 'The message could not be sent. Please try again.',
    verifiedMessage: (person: string, company: string, link: string, hasAccount: boolean) => hasAccount
      ? `Hello ${person}, this is the Tarmem team.\n${company}'s account is verified and ready to use. Sign in with the email and password you created:\n${link}`
      : `Hello ${person}, this is the Tarmem team.\n${company}'s application is accepted. To finish, create your account on the contractor page:\n${link.replace('/signin', '/join')}`,
    coPendingTitle: 'Your account is being verified', coPendingNote: 'We have your application and your account is created. The Tarmem team reviews your details and contacts you on your mobile; you get an email the moment the account is live. Open projects then appear here.',
    choseNote: 'You chose the bid from {co}. The Tarmem team will contact you and the contractor to complete the agreement and start the work.', chosenNote: 'The homeowner chose your bid. The Tarmem team will contact you to complete the agreement and start the work.',
    nextArrange: 'The Tarmem team will contact you both to arrange the first payment and the start of work; the Payments tab has the details.',
    paySoonTitle: 'Payment on the site is being set up', paySoonNote: 'Both sides have signed the agreement; it is saved with your names and the time of each signature. The Tarmem team will contact you both to arrange the first payment and start the work. Once payment on the site is live, payments are made here and released as each stage is approved.', refresh: 'Check payment status',
    paySoonNoteCo: 'Payment on the site is being set up. The Tarmem team will contact you to arrange payments; your payouts will show here once it is live.', payStillOff: 'Payment on the site is not live yet. The Tarmem team will contact you both to arrange payments.',
    stagesAfterAward: 'Stages start once the project is awarded to a contractor.',
    stagesSoon: 'Stages start once the first payment is arranged. Approving stages and releasing their payments on the site goes live together with payment.',
    settingsMobileNote: 'Used to reach you, and for WhatsApp updates.', settingsEmail: 'Email (you sign in with it)',
    protectNoNafath: 'The Tarmem team reviews the business details and its commercial registration before the profile goes live.',
    postedNoBidsWa: 'Your project is posted and verified contractors can see it now. Their bids appear here as they arrive, and you get an email and a WhatsApp with each new bid.',
    msgsNoThread: 'Messaging with a contractor opens with the first bid on your project.', msgsEmpty: 'No messages yet. Write the first one; the other side is told by email and WhatsApp.', msgsWith: 'Conversation with', msgFailed: 'The message could not be sent. Try again.', msgsHomeowner: 'The homeowner', msgsContractor: 'The contractor',
    msgsSoon: 'Messaging inside the project is being set up. Until then the Tarmem team reaches you both by email and WhatsApp; the bids, the agreement and the files stay here.', msgsFrom: 'Tarmem',
    waSub: 'Tarmem sends your project updates to WhatsApp: new bids, an accepted bid, the signed agreement and stages. Each message has a button that opens the project.', waNumberNote: 'This is your account\'s mobile number; changing it here changes it on your account too.',
    waPreview: 'Status update for your project P-2001 on Tarmem: bid number 3 was received from Build Co, SAR 52,000, 30 days. The details are on the project page. [Open the project]',
    settingsSaved: 'Your settings are saved.', emailLocked: 'To change the email you sign in with, message the Tarmem team.', closeTopic: 'Account closure request', closeBody: 'The account holder asks for their account to be closed.',
    companyLocked: 'The company name is the one Tarmem verified and cannot be changed here. Put it back as it was; to change it, message the Tarmem team.', noWorkYet: 'No projects completed through Tarmem yet', noReviewsYet: 'No reviews yet',
    pfAdd: 'Add photos of your work', pfCaption: 'A short caption for the next photos (optional)', pfCaptionPh: 'e.g. Kitchen in Al Arid, 2026', pfHint: 'Up to 12 photos, JPG or PNG, 8 MB each. Homeowners comparing bids see them.', pfRemove: 'Remove', pfFull: 'You have reached the limit (12 photos). Remove one to add another.', pfFailed: 'The photo could not be uploaded. Try again.',
    wrTitle: 'Requests awaiting confirmation', wrNote: 'A request stays here until you have confirmed the money with the payment provider or the bank. Confirming records it in the person\'s wallet; rejecting cancels it.', wrNone: 'No requests are waiting.', wrDeposit: 'Deposit', wrPayout: 'Payout', wrConfirm: 'Confirm received', wrPaid: 'Mark as paid', wrReject: 'Reject',
    coRefresh: 'Check again', bidsSoonTitle: 'Bidding opens soon', bidsSoonNote: 'Your account is verified and you can browse open projects. Bidding on the site is about to launch; until then, message the Tarmem team about a project you want.',
    coPassword: 'Choose a password for your account', coEmailNeeded: 'Enter your email: you sign in with it once verified.', coCreate: 'Send application and create account',
    uploading: 'Uploading files…', uploadFailed: 'This file could not be uploaded. Try again from the Files tab.',
    fileErr: { type: 'Allowed files: JPG and PNG images, and PDF files.', size: 'A file can be 10 MB at most.', count: 'A project can hold 10 files at most.' },
    joinSent: 'We have your application. Tarmem\'s team will contact you to complete verification.', joinSend: 'Send application', inbox: 'Inbox', inboxOpen: 'Open the inbox: projects, applications, messages →',
    confirmTitle: 'Check your email to activate your account',
    confirmLede: (email: string) => `We sent an activation link to ${email}. Open it to activate your account and sign in, even on another device. If it is not in your inbox, check your spam folder.`,
    confirmDraft: 'Your project is saved on this device and is posted as soon as you activate your account and sign in on it.',
    confirmCo: 'We have your application. Once your account is active, the Tarmem team reviews your details and contacts you on your mobile.',
    // (031) explore first, verify before dealing: the banner for an account that cannot deal yet, and what the link says
    verifyBarHo: (email: string) => `Confirm your email so contractors can see your project and you can message them and accept a bid. We sent the link to ${email}.`,
    verifyBarCo: (email: string) => `Confirm your email to send bids and message homeowners. We sent the link to ${email}.`,
    verifyBarProfile: 'Complete your account in Settings (your name and mobile number) to start dealing on Tarmem.',
    verifyBarOtp: 'Verify your mobile number in Settings to start dealing on Tarmem.',
    verifyResend: 'Send the link again', verifyCheck: 'I have confirmed', verifySettings: 'Settings',
    verifySent: 'We sent a new link. Check your inbox, and your spam folder.',
    verifyRate: 'We sent several links in the last hour. Wait a little, then try again.',
    verifyNotYet: 'Your email is not confirmed yet. Open the link we sent you.',
    verifiedNow: 'Your email is confirmed. Your account is ready to deal now.',
    verifiedSignIn: 'Your email is confirmed. Sign in to continue.',
    verifyExpired: 'This confirmation link has expired. Sign in and ask for a new one from the bar at the top of the page.',
    verifyInvalid: 'This confirmation link is not valid. Sign in and ask for a new one from the bar at the top of the page.',
    postedHeld: 'Your project is saved. Contractors will see it once you confirm your email with the link we sent you; it appears to them automatically.',
    tsSetupTitle: 'Turn on two-step sign-in for the console',
    tsSetupLede: 'To protect the admin console, a code from an authenticator app on your phone is asked for after your password. You set it up once.',
    tsStep1: 'Install an authenticator app on your phone, such as Google Authenticator or Microsoft Authenticator.',
    tsStep2: 'In the app, choose “Add account”, then scan this code.',
    tsStep3: 'Type the six-digit code the app shows.',
    tsQrAlt: 'QR code that adds Tarmem to your authenticator app', tsNoScan: 'Cannot scan it? Enter this key in the app instead:',
    tsCopy: 'Copy key', tsCopied: 'Copied', tsLoading: 'Preparing your set-up code…', tsRetry: 'Try again',
    tsCode: 'Code from the app', tsTurnOn: 'Turn on and continue',
    tsTitle: 'Two-step sign-in', tsLede: 'Type the six-digit code your authenticator app shows now.', tsContinue: 'Continue',
    tsSignOut: 'Sign out',
    tsLost: 'Lost your phone? Two-step sign-in is removed in the Supabase dashboard (Authentication, Users, the account, Remove MFA factors); you then set it up again here when you sign in.',
    tsDone: 'Two-step sign-in is on. The console asks for a code from the app each time you sign in.',
    resend: 'Send the link again', resent: 'We sent the link again. It can take a minute to arrive.', confirmedWelcome: 'Your account is active. Welcome to Tarmem.',
    linkExpiredTitle: 'This link has expired or was already used', linkExpiredLede: 'Activation and reset links work once, for a limited time. Enter your email and we will send you a new one.',
    linkSendSignup: 'Send a new activation link', linkSendReset: 'Send a new reset link', linkOr: 'or',
    linkSentSignup: 'If the account is waiting to be activated, a new link arrives within minutes. Check your spam folder too.',
    draftPhotos: 'Your project is posted. The photos you chose before activating your account were not kept on this device; add them from the project\'s Files tab.',
    notHomeownerPost: 'Contractor accounts cannot post projects. To request work on your own home, create a homeowner account with another email.',
    signedArrange: 'Signed · the Tarmem team arranges the start', statusOpen: 'Open for bids', statusCompleted: 'Completed', statusWithdrawn: 'Withdrawn',
    msgsNoThreadCo: 'Messaging with the homeowner opens once you submit your bid.',
    nextCta: { bids: 'Compare bids', bid: 'Submit your bid', agreement: 'Review the agreement', messages: 'Open messages', stages: 'Open stages', payments: 'Open payments', review: 'Review the contractor', complete: 'Confirm the work is complete', files: 'Add photos' },
    nextSignedHo: 'The Tarmem team contacts you both to arrange the start. Keep in touch with the contractor in Messages, and confirm the work here once it is finished.',
    nextSignedCo: 'The Tarmem team contacts you both to arrange the start. Coordinate the details with the homeowner in Messages, and confirm the work here once it is finished.',
    nextPendingHo: 'You signed the agreement; it is waiting for the contractor\'s signature. You will be notified when they sign.',
    nextPendingCo: 'The homeowner chose your bid and signed the agreement. Review and sign it, and the project is yours.',
    nextDoneHo: 'The project is complete. Share your review of the contractor.', nextDoneCo: 'The project is complete. Thank you for working with Tarmem.', nextReviewed: 'The project is complete, and thank you for your review.',
    stagesPlanned: 'Stages start once the first payment is arranged',
    acceptedTitle: 'The accepted bid', acceptedChosen: 'You chose it and the agreement is signed on it', acceptedChosenCo: 'The homeowner chose it and the agreement is signed on it', acceptedSplit: 'Payment split across the stages', acceptedVat: 'The contractor is VAT-registered, so 15% VAT is added to this value', acceptedVisit: 'Includes a site visit before the start',
    plannedTitle: 'Planned stages', plannedNote: 'Stages start once the first payment is arranged with the Tarmem team. Approving stages and releasing their payments on the site goes live together with payment.', plannedWaiting: 'Planned',
    completeTitle: 'Is the work finished?', completeNote: 'When the contractor has finished the agreed work, confirm it here. The project is recorded as complete once the contractor confirms too, and you can then review them.',
    completeTitleCo: 'Have you finished the work?', completeNoteCo: 'When you have finished the agreed work, confirm it here: the homeowner is asked to check it and confirm. The project is recorded as complete once both of you have.',
    completeBtn: 'Confirm the work is complete', completeQ: 'Confirm that the work is complete? This step cannot be undone.', completeYes: 'Yes, the work is complete', completeNo: 'Not yet',
    completeWaitHo: 'Your confirmation is recorded; we are waiting for the contractor to confirm. The project is recorded as complete as soon as they do.',
    completeWaitCo: 'Your confirmation is recorded; we are waiting for the homeowner to check the work and confirm. The project is recorded as complete as soon as they do.',
    completeAskHo: 'The contractor confirmed the work is complete. Check it: if it is, confirm here, and the project is recorded as complete and you can review the contractor. If something is left, message them from the Messages tab.',
    completeAskCo: 'The homeowner confirmed the work is complete. Confirm it too, and the project is recorded as complete.',
    completeWaitTagHo: 'Waiting for the contractor', completeWaitTagCo: 'Waiting for the homeowner', completeTheirsHo: 'Confirmed by the contractor', completeTheirsCo: 'Confirmed by the homeowner',
    completeSent: 'Your confirmation is recorded, and the other party has been asked to confirm too.',
    completeDone: 'The project is recorded as complete. Share your review of the contractor.', completeDoneCo: 'The project is recorded as complete. Thank you for working with Tarmem.',
    coDeclinedTitle: 'Your application was not approved', coDeclinedNote: 'The Tarmem team reviewed your application and did not approve it. If you have a question or new information about your business, message us and we will look at it again.', coDeclinedContact: 'Contact the Tarmem team',
    admPayOffCodes: 'Payment on the site is not live yet: codes are saved and managed here, and can be used once it is.',
    admPayOffPartners: 'Clicks and sign-ups from partner links are not counted yet, so those figures show “—” until payment on the site is live.',
    admPayOffLate: 'Late deliveries and refunds are recorded here once stage payments start on the site; nothing is recorded yet.',
    admSender: 'Sender', admNoApplication: 'No application', admPreview: 'Sample', admApp: { new: 'New', contacted: 'Contacted', verified: 'Verified', declined: 'Declined' } as Record<string, string>,
    admSar: 'SAR', admCr: 'CR', admDays: 'days', admChosen: 'chosen by the customer',
    adminCtlTitle: 'Tarmem team actions',
    adminCtlOpen: 'This project is open for bids. Remove it if it is a duplicate, spam or against the rules: it comes off the site, and its owner and everyone who bid are told by email.',
    adminCtlActive: 'This project is signed and in progress. Mark it completed once the work is handed over, or cancel it if the work has stopped. Both parties are told by email either way.',
    adminComplete: 'Mark as completed', adminCompleteQ: 'Mark the project as completed? The homeowner can then review the contractor. This cannot be undone.', adminCompleteYes: 'Yes, mark it completed', adminCompleted: 'The project is marked completed, and both parties have been emailed.',
    adminCancel: 'Cancel the project', adminCancelQ: 'Cancel the project? It is recorded as withdrawn and does not continue on the site. This cannot be undone.', adminCancelYes: 'Yes, cancel it', adminCancelled: 'The project is cancelled, and both parties have been emailed.',
    adminRemove: 'Remove the project', adminRemoveQ: 'Remove the project from the site? It is no longer open for bids. This cannot be undone.', adminRemoveYes: 'Yes, remove it', adminRemoved: 'The project is removed; its owner and everyone who bid have been emailed.',
    adminKeep: 'Go back', adminNoteLabel: 'Internal note (optional)', adminNotePh: 'The reason, for the team\'s record only. It is never sent to anyone.',
    msgsAdminRead: 'You are reading this conversation only: nothing can be sent from here, and nothing is marked as read for anyone.', msgsNoneYet: 'No messages in this project yet.',
    prefsCo: { pNewProjects: 'New projects in my trades (coming soon)', pBidChosen: 'My bid is chosen and the agreement signed', pMsg: 'New messages', pChanges: 'Change requests' },
    pwTitle: 'Password', pwNote: 'Change the password you sign in with. You stay signed in here; your other devices are signed out.', pwChange: 'Change password', pwSave: 'Save password', pwSaved: 'Your password is changed, and your other devices are signed out.', pwCancel: 'Cancel',
    emailReadOnly: 'The email you sign in with cannot be changed here. To change it, message the Tarmem team.',
    withdrawFailed: 'The project could not be withdrawn and is still posted. Try again.', reviewFailed: 'Your review could not be saved. Try again.', saveFailed: 'The contractor could not be saved to your list. Try again.',
    signFailed: 'Your signature could not be saved.', filesRefused: 'Not uploaded', filesEmpty: 'No files yet.',
    pfType: 'Allowed photos: JPG, PNG and WebP.', pfSize: 'A photo can be 8 MB at most.',
    chars: (n: number, max: number) => `${n.toLocaleString('en-US')} / ${max.toLocaleString('en-US')}`,
  },
} as const;

export type PlatformLang = keyof typeof PLATFORM_COPY;
export type PlatformError = keyof typeof PLATFORM_COPY['en']['err'];
